# ============ 投票系统配置文件 ============

# 2captcha 验证码服务配置
captcha:
  api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"  # 2captcha API密钥

# Bright Data 代理配置
proxy:
  host: "brd.superproxy.io"
  port: 33335
  user: "brd-customer-xxxxxxxxxxxxxxxxxxxxxx-country-jp"
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# 投票目标配置
voting:
  base_url: "https://gtop100.com/MapleStory/MapleSchool-101860?vote=1&pingUsername={username}"
  post_url: "https://gtop100.com/home/send_vote/"
  
# 要投票的账号列表
accounts:
  - "abcdefg"
  - "abcdefg2" 
  - "abcdefg3"
  - "abcdefg4"
  - "abcdefg5"
  # 在这里添加更多账号...

# 浏览器配置
browser:
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
  window_size:
    width_min: 1200
    width_max: 1920
    height_min: 800
    height_max: 1080
  # headless: false  # 是否无头模式运行

# 任务执行配置
execution:
  max_rounds: 3  # 最大重试轮数
  delay_between_accounts:
    min: 1  # 账号间最小延时（秒）
    max: 10  # 账号间最大延时（秒）
  voting_behavior_delay:
    min: 5.0  # 模拟真实投票行为的最小等待时间（秒）
    max: 10.0  # 模拟真实投票行为的最大等待时间（秒）

# 日志配置
logging:
  rotation: "1 day"  # 日志轮转周期
  retention: "7 days"  # 日志保留时间
  level: "INFO"  # 日志级别
  encoding: "utf-8"  # 日志编码 